apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-scv
  namespace: hello-kubernetes
  team: forward-deployed-engineering
  contact: jane.smith@acme.com

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hello-kubernetes